# Generated by Django 3.2 on 2021-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_review_description_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description_review',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='description'),
        ),
    ]
